D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\gen\com\lge\handwritingime\R.java \
 : D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_pen_type_ballpen.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_pen_type_brush.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_pen_type_inkpen.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_pen_type_pencil.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_candidate_down_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_candidate_up_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_alpha.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_etc.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_han.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_hiragana.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_kanji.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_katakana.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_char_candidate_number.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_keypad_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_lang_mode_char.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_lang_mode_check.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_lang_mode_text.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_lang_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more_clip.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more_delete_all.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more_delete_one.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more_delete_stroke.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more_keyboard_input.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_more_setting.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\button_state_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\color_picker_border.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\popup_key_feedback.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\screen_left_button_state.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable\screen_right_button_state.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon_kbd.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon_setting.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon_sym.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_help_input_language.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_help_numeric_and_symbol.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_help_onehand_operation.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_help_split_keypad.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_help_use_function_key.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_4way.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_del.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_del_stroke.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_enter.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_left.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_right.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-land-xxhdpi\hw_ime_keypad_icon_space_large.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon_kbd.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon_setting.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon_sym.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_help_input_language.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_help_numeric_and_symbol.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_help_onehand_operation.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_help_split_keypad.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_help_use_function_key.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_4way.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_del.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_del_stroke.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_enter.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_left.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_right.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-port-xxhdpi\hw_ime_keypad_icon_space_large.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_editor_btn_effect_character_body_bottom.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_editor_btn_effect_character_body_mid.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_editor_btn_effect_character_title_mid.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_editor_btn_effect_character_title_top.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ic_page_view_off.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ic_page_view_on.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_btn_effect_character.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_btn_effect_character_press.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_btn_effect_line_ver.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_btn_func_more_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_btn_func_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_btn_func_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_color_box_selected.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_alpha.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_alpha_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_chinese.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_chinese_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_etc.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_etc_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_han.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_han_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_hiragana.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_hiragana_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_katakana.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_katakana_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_number.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_btn_number_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_alphabet.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_han.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_hiragana.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_kanji.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_katakana.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_none.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_number.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_hw_popup_word_symbol_ja.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_bg.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_btn_more_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_candidate_down_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_candidate_down_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_candidate_up_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_candidate_up_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_area.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_bg.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_left_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_left_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_recommand_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_recommand_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_right_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_handwriting_right_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_01.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_02.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_03.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_04.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_05.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_06.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_check_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_check_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_char_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_char_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_text_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_text_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_setting_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_setting_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_clip_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_clip_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_all_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_all_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_one_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_one_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_stroke_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_stroke_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_handwriting_kbd_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_handwriting_kbd_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_kbd_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_kbd_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_setting_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_ime_keypad_input_icon_setting_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_keyboard_language.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_ballpen.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_ballpen_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_ballpen_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_bg.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_brush.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_brush_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_brush_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_inkpen.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_inkpen_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_inkpen_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_pencil.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_pencil_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_popup_pen_type_pencil_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_scrubber_control_disabled_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_scrubber_control_focused_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_scrubber_control_normal_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_scrubber_control_pressed_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_scrubber_primary_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\drawable-xxhdpi\hw_scrubber_track_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\color_picker_layout.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\handwriting_ime.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\ime_help.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\ime_help_main.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\pen_type_dialog.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\scroll_delay_seekbar_dialog.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\select_delete_button_popup_layout.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\select_keyboard_popup_layout.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout\select_language_setting_popup_layout.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\layout-land\ime_help.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\arrays.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\attrs.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\colors.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\dimens.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\donottranslate.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\integers.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values\style.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values-ja\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values-ko\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\values-land\dimens.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\xml\method.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\res\xml\settings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon_kbd.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon_setting.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_handwriting_icon_sym.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_help_input_language.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_help_numeric_and_symbol.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_help_onehand_operation.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_help_split_keypad.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_help_use_function_key.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_4way.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_del.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_del_stroke.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_enter.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_left.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_right.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-land-xxhdpi\hw_ime_keypad_icon_space_large.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon_kbd.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon_setting.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_handwriting_icon_sym.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_help_input_language.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_help_numeric_and_symbol.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_help_onehand_operation.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_help_split_keypad.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_help_use_function_key.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_4way.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_del.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_del_stroke.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_enter.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_left.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_right.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-port-xxhdpi\hw_ime_keypad_icon_space_large.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_editor_btn_effect_character_body_bottom.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_editor_btn_effect_character_body_mid.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_editor_btn_effect_character_title_mid.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_editor_btn_effect_character_title_top.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ic_page_view_off.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ic_page_view_on.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_btn_effect_character.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_btn_effect_character_press.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_btn_effect_line_ver.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_btn_func_more_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_btn_func_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_btn_func_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_color_box_selected.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_alpha.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_alpha_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_chinese.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_chinese_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_etc.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_etc_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_han.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_han_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_hiragana.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_hiragana_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_katakana.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_katakana_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_number.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_btn_number_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_alphabet.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_han.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_hiragana.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_kanji.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_katakana.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_none.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_number.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_hw_popup_word_symbol_ja.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_bg.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_btn_more_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_candidate_down_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_candidate_down_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_candidate_up_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_candidate_up_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_area.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_bg.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_left_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_left_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_recommand_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_recommand_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_right_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_handwriting_right_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_01.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_02.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_03.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_04.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_05.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_help_btn_image_06.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_check_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_check_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_char_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_char_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_text_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_hw_text_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_setting_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_icon_popup_setting_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_clip_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_clip_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_all_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_all_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_one_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_one_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_stroke_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_del_stroke_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_handwriting_kbd_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_handwriting_kbd_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_kbd_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_kbd_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_setting_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_ime_keypad_input_icon_setting_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_keyboard_language.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_ballpen.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_ballpen_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_ballpen_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_bg.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_brush.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_brush_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_brush_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_inkpen.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_inkpen_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_inkpen_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_pencil.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_pencil_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_popup_pen_type_pencil_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_scrubber_control_disabled_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_scrubber_control_focused_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_scrubber_control_normal_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_scrubber_control_pressed_holo.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_scrubber_primary_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\res\drawable-xxhdpi\hw_scrubber_track_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\AndroidManifest.xml \
