D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\gen\com\lge\emoji\R.java \
 : D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\anim\decoemojilist_close_enter.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\anim\decoemojilist_close_exit.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\buttons_background_type1.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\button_state_keypad_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\button_state_normal.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\button_state_page_left.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\button_state_page_right.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\image_stateful.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\switch_emoji_tab_center.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\switch_emoji_tab_center_no_select.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\switch_emoji_tab_left.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\switch_emoji_tab_left_no_select.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\switch_emoji_tab_right.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable\switch_emoji_tab_right_no_select.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\buttons_background_type1_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\buttons_background_type1_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\dummy_icon_microphone.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\icon.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ic_list_attachment.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ic_menu_recent_history_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ic_skin_set_camera.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ic_skin_set_gallery.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ic_skin_set_select.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ic_skin_set_setting.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ime_keypad_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ime_keypad_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ime_keypad_emoji_left_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ime_keypad_emoji_left_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ime_keypad_emoji_right_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\ime_keypad_emoji_right_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\keyboard_background.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\page_not.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-hdpi\page_select.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-ja-hdpi\button_ok.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\ab_command_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\bg_w.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\btn_command_normal_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\btn_command_pressed_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\dark_header_title.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_icon_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_icon_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_icon_03_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_icon_03_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_lead_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_lead_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_lead_02_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_lead_02_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_main_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_main_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_title_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_title_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_title_02_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\deco_title_02_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\emojidownloader.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\ic_launcher.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\list_section_divider_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\main_visual_back.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\main_visual_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xhdpi\main_visual_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_btn_effect_character.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_btn_func_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_btn_func_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_center_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_center_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_left_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_left_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_right_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_right_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_symbol_bg.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_symbol_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_keypad_symbol_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_del.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_down.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_dpict.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_emotion.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_line.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_pict.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_symbol.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_text.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_up.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_icon_upict.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_tab_divider_vertical.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_tab_selected_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_tab_selected_pressed_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_tab_unselected_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\ime_symbol_tab_unselected_pressed_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\key_12key_space.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\key_qwerty_space.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\tab_no_select.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\tab_press.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\drawable-xxhdpi\tab_select.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\layout\decome_down_loadder_layout.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\layout\emoji_list.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\layout\emoji_page.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\layout\setting_popup_layout.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\arrays.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\colors.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\dimens.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\donottranslate.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\emoji_docomo.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values\styles.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values-hdpi\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values-ja\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values-land\dimens.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values-ldpi\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\values-mdpi\strings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\xml\method.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\res\xml\settings.xml \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\buttons_background_type1_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\buttons_background_type1_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\dummy_icon_microphone.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\icon.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ic_list_attachment.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ic_menu_recent_history_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ic_skin_set_camera.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ic_skin_set_gallery.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ic_skin_set_select.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ic_skin_set_setting.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ime_keypad_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ime_keypad_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ime_keypad_emoji_left_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ime_keypad_emoji_left_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ime_keypad_emoji_right_btn_normal.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\ime_keypad_emoji_right_btn_pressed.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\keyboard_background.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\page_not.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-hdpi\page_select.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-ja-hdpi\button_ok.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\ab_command_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\bg_w.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\btn_command_normal_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\btn_command_pressed_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\dark_header_title.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_icon_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_icon_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_icon_03_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_icon_03_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_lead_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_lead_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_lead_02_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_lead_02_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_main_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_main_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_title_01_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_title_01_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_title_02_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\deco_title_02_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\emojidownloader.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\ic_launcher.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\list_section_divider_holo_light.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\main_visual_back.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\main_visual_f1.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xhdpi\main_visual_f2.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_btn_effect_character.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_btn_func_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_btn_func_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_center_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_center_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_left_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_left_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_right_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_btn_symbol_emoticon_category_right_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_symbol_bg.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_symbol_btn_normal.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_keypad_symbol_btn_pressed.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_del.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_down.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_dpict.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_emotion.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_line.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_pict.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_symbol.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_text.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_up.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_icon_upict.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_tab_divider_vertical.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_tab_selected_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_tab_selected_pressed_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_tab_unselected_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\ime_symbol_tab_unselected_pressed_holo.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\key_12key_space.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\key_qwerty_space.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\tab_no_select.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\tab_press.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\res\drawable-xxhdpi\tab_select.9.png \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\AndroidManifest.xml \
