D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\bin\iWnnIME-debug-unaligned.apk : \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\bin\iWnnIME.ap_ \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\bin\classes.dex \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\bin\classes.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\bin\classes.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\libs\emojisl_type2.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\dcmvoiceeditorapi.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\DecoEmojiInterface.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\libs\com.visionobjects.im.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\lib.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\Framework_CliptrayService.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\libs\lghwime_lib_out.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\WnnConnector.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\lg_system_service.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGEmoji_libout_omron\libs\lgemoji_lib_out.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\libs\android-support-v4.jar \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libEnjemailuri.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjcon.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjubase1.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjubase1gb.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjubase1us.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjubase2.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjubase3.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libennjyomi.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libiwnn.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libkaomoji_kihon.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libkaomoji_tyukyu.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libkoKRnjcon.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libkoKRnjexyomi.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libkoKRnjubase1.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libkoKRnjubase2.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjaddress.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjcon.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjemoji.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjexyomi.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjfzk.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjname.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjtan.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjubase1.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libnjubase2.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\libstandardnjemailuri.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_en_tablet_USUK.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_en_USUK.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_ja_JP.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_ja_xlarge_JP.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_ko_KR.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_ko_xlarge_KR.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\ime\sources\libs\armeabi\lib_dic_morphem_ja_JP.conf.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\libs\armeabi\libMyScriptEngine.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\libs\armeabi\libMyScriptHWR.so \
D:\model\iWnnIME\Env\snapshot_src_for_lg\LGHWIME_libout\libs\armeabi\libvoim.so \
